#title in header
title: "Hi Folks."

#main info
#owner
owner: "I am Sanjay Bhat"
email: sanjubhat2004@gmail.com
info: "A 3rd year Computer Science student at NITK."
#description
desc: "This is my blog, where I talk about stuff I find interesting, which might be from tech, or non-tech."

#menu
menu:
  # Works: /Works
  # About: /About

#index/main page max show posts (in number)
max_post: 4

# Colors use hex color without #
# Theme color
tcolor: 0FA0CE

# Define path to user css
#(could be also located outside of theme)
# Relative to source/ directory
usercss: css/user.css

# social profile at the footer/bottom
footer: true
placename: Earth
placelink: https://en.wikipedia.org/wiki/Earth
github: https://github.com/sanjaybhat2004
linkedin: https://www.linkedin.com/in/sanjay-bhat-6b364a250/

# Misc
nanobar: /js/nanobar.min.js
switch_light: ☀️
switch_dark: 🌑

# Picture enlargement
picjs: /js/pic.min.js

# favicon
favicon: /images/favicon.png
# thumbnail
thumbnail: /images/thumbnail.jpg

article:
  thumbnail: true

# DISQUS comments (sign up to Disqus to get disqus_shortname)
disqus_enabled: false
disqus_shortname: https-adisaktijrs-github-io
